Repository Steveplays28/restart-server, pull requests merged in 2023-04, with the labels that each got.

#10 restart warns and disconnect message
  gradle.properties
  src/main/java/io/github/steveplays28/restartserver/RestartScheduler.java
  src/main/java/io/github/steveplays28/restartserver/commands/RestartCommand.java
  src/main/java/io/github/steveplays28/restartserver/config/RestartServerConfig.java
  src/main/resources/fabric.mod.json
Labels: enhancement

#11 Add GitHub workflow for testing and building artifacts after a commit/PR
  .github/workflows/main.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/test/java/io/github/steveplays28/restartserver/gametest/GameTests.java
  src/test/resources/assets/restart-server/icon.png
  src/test/resources/fabric.mod.json
Labels: ci/cd

#9 backport to 1.18.2
  gradle.properties
  src/main/java/io/github/steveplays28/restartserver/RestartScheduler.java
  src/main/java/io/github/steveplays28/restartserver/commands/RestartCommand.java
  src/main/resources/fabric.mod.json
Labels: bug, enhancement
